apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: localdev
data:
  nats-server.conf: |
    port: 4222
    cluster {
      port: 6222
      name: "nats-cluster"
    }
    debug: true
    trace: true
    logtime: true
    max_payload: 1048576  # 1MB
    max_connections: 1000
    max_control_line: 512 