apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: localdev
spec:
  type: ClusterIP 
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
      targetPort: 4222
    - name: cluster
      port: 6222
      targetPort: 6222