apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: localdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:latest
          command: ["/nats-server"]
          args: ["--config", "/etc/nats/nats-server.conf"]
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          ports:
            - name: client
              containerPort: 4222
            - name: cluster
              containerPort: 6222
          volumeMounts:
            - name: nats-config
              mountPath: /etc/nats/nats-server.conf
              subPath: nats-server.conf
      volumes:
        - name: nats-config
          configMap:
            name: nats-config
            items:
              - key: nats-server.conf
                path: nats-server.conf