apiVersion: v1
kind: Service
metadata:
  name: dualwrites-service
  namespace: localdev
spec:
  type: ClusterIP
  selector:
    app: dualwrites
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
